//
//  RelistenAlbumArts.h
//  PhishOD
//
//  Created by Alec Gorge on 9/27/15.
//  Copyright (c) 2015 Blue Paint, LLC. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface RelistenAlbumArts : NSObject

// Drawing Methods
+ (void)drawShatterExplosionWithBaseColor:(UIColor * _Nonnull)color
                                     date:(NSString * _Nullable)dateStr
                                    venue:(NSString * _Nullable)venueStr
                                 location:(NSString * _Nullable)locationStr
                                drawLabel:(BOOL)drawLabel;

+ (void)drawRandomFlowersWithBaseColor:(UIColor * _Nonnull)color
                                  date:(NSString * _Nullable)dateStr
                                 venue:(NSString * _Nullable)venueStr
                              location:(NSString * _Nullable)locationStr
                             drawLabel:(BOOL)drawLabel;

+ (void)drawSplashWithBaseColor:(UIColor * _Nonnull)color
                           date:(NSString * _Nullable)dateStr
                          venue:(NSString * _Nullable)venueStr
                       location:(NSString * _Nullable)locationStr
                      drawLabel:(BOOL)drawLabel;

+ (void)drawCityGlittersWithBaseColor:(UIColor * _Nonnull)color
                                 date:(NSString * _Nullable)dateStr
                                venue:(NSString * _Nullable)venueStr
                             location:(NSString * _Nullable)locationStr
                            drawLabel:(BOOL)drawLabel;

@end
