//
//  RelistenShardStyle.h
//  PhishOD
//
//  Created by Alec Gorge on 9/25/15.
//  Copyright (c) 2015 Blue Paint, LLC. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface RelistenShardStyle : NSObject

// Drawing Methods
+ (void)drawCanvas1WithColors:(NSArray<UIColor *> *)colorsDarkToLight
                         date:(NSString *)dateStr
                        venue:(NSString *)venueStr
                  andLocation:(NSString *)locationStr;

@end
