name: iOS CI

on:
  push:
    branches: 
        - '**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Relisten for the iOS Simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Dependencies 
        run: |
          ./setup.sh
      - name: Build
        run: |
          ./xcodebuild.sh
