name: iOS CI

on:
  push:
    branches: 
        - '**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Relisten for the iOS Simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bundler Cache
        uses: actions/cache@v2
        with:
            path: vendor/bundle
            key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
            restore-keys: |
                ${{ runner.os }}-gems-
      - name: Setup Bundler
        run: |
            gem install bundler
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 3
      - name: Cocoapods Cache
        uses: actions/cache@v2
        with:
            path: Pods
            key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
            restore-keys: |
                ${{ runner.os }}-pods-
      - name: Setup Dependencies
        run: |
          ./setup.sh
      - name: Build
        run: |
          ./xcodebuild.sh
      - name: Test
        run: |
          ./xcodebuild.sh test
